In [1]:
import pandas as pd 
from sklearn.feature_selection import VarianceThreshold

In [2]:
df=pd.read_csv('santander.csv',nrows=10000)

In [3]:
df.head()

   ID  var3  var15  imp_ent_var16_ult1  ...  saldo_medio_var44_ult1  saldo_medio_var44_ult3          var38  TARGET
0   1     2     23                 0.0  ...                     0.0                     0.0   39205.170000       0
1   3     2     34                 0.0  ...                     0.0                     0.0   49278.030000       0
2   4     2     23                 0.0  ...                     0.0                     0.0   67333.770000       0
3   8     2     37                 0.0  ...                     0.0                     0.0   64007.970000       0
4  10     2     39                 0.0  ...                     0.0                     0.0  117310.979016       0

[5 rows x 371 columns]

In [5]:
df.shape

(10000, 371)

In [57]:
X=df.drop(labels=['TARGET'], axis=1)
y=df['TARGET']

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.3)

In [59]:
var_threshold=VarianceThreshold(0)
var_threshold.fit(x_train)

VarianceThreshold(threshold=0)

In [60]:
len(var_threshold.get_feature_names_out())    #take only columns that doesnot have 0 varience

284

In [61]:
var_threshold.get_support()          # return as true and false weather varience is zero -->False

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True, False,  True, False, False, False, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True, False, False, False, False,  True,  True,
       False,  True, False, False, False,  True, False, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True, False, False, False,  True, False, False, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [62]:
col_Not_select=[feature for feature in x_train.columns 
           if feature not in x_train.columns[var_threshold.get_support()]]

In [63]:
len(col_Not_select)

86

In [64]:
len([feature for feature in x_train.columns if feature not in var_threshold.get_feature_names_out()])    # same as above

86

In [65]:
x_train.drop(col_Not_select,axis=1,inplace=True)

In [66]:
x_train

         ID  var3  var15  ...  saldo_medio_var44_ult1  saldo_medio_var44_ult3      var38
7681  15431     2     42  ...                     0.0                     0.0   37491.21
9031  18181     2     31  ...                     0.0                     0.0  106685.94
3691   7411     2     51  ...                     0.0                     0.0   66144.66
202     407     2     36  ...                     0.0                     0.0   92121.36
5625  11280     2     23  ...                     0.0                     0.0   74650.83
...     ...   ...    ...  ...                     ...                     ...        ...
9225  18564     2     33  ...                     0.0                     0.0  117547.89
4859   9723     2     24  ...                     0.0                     0.0   71050.83
3264   6557     2     24  ...                     0.0                     0.0  141069.33
9845  19796     2     38  ...                     0.0                     0.0   86412.15
2732   5441     2     23  ...                     0.0                     0.0   45985.68

[7000 rows x 284 columns]

In [70]:
# for train 
x_test=pd.DataFrame(var_threshold.transform(x_test),columns=var_threshold.get_feature_names_out())

In [71]:
x_test.head()

        ID  var3  var15  ...  saldo_medio_var44_ult1  saldo_medio_var44_ult3          var38
0  18882.0   2.0   23.0  ...                     0.0                     0.0   75170.310000
1   1778.0   2.0   79.0  ...                     0.0                     0.0   57855.510000
2   4806.0   2.0   38.0  ...                     0.0                     0.0  117310.979016
3  11854.0   2.0   48.0  ...                     0.0                     0.0   50659.230000
4   4697.0   2.0   23.0  ...                     0.0                     0.0   43843.320000

[5 rows x 284 columns]