In [16]:
import pandas as pd 
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

In [17]:
df=pd.read_csv("titanic.csv")
df.head(10)

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [18]:
df.isnull().mean()*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [19]:
df.drop(columns=['Cabin','SibSp','Embarked','Name' , 'Sex' , "Ticket"], inplace=True)

In [20]:
df.head(1)

   PassengerId  Survived  Pclass   Age  Parch  Fare
0            1         0       3  22.0      0  7.25

In [22]:
It=IterativeImputer(estimator=RandomForestRegressor(),max_iter=10, random_state=42)
df_impte=It.fit_transform(df)
df_impte

C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\impute\_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

array([[  1.    ,   0.    ,   3.    ,  22.    ,   0.    ,   7.25  ],
       [  2.    ,   1.    ,   1.    ,  38.    ,   0.    ,  71.2833],
       [  3.    ,   1.    ,   3.    ,  26.    ,   0.    ,   7.925 ],
       ...,
       [889.    ,   0.    ,   3.    ,  18.0683,   2.    ,  23.45  ],
       [890.    ,   1.    ,   1.    ,  26.    ,   0.    ,  30.    ],
       [891.    ,   0.    ,   3.    ,  32.    ,   0.    ,   7.75  ]],
      shape=(891, 6))

In [29]:
df_new=pd.DataFrame(df_impte)
df_new.head(10)

      0    1    2      3    4        5
0   1.0  0.0  3.0  22.00  0.0   7.2500
1   2.0  1.0  1.0  38.00  0.0  71.2833
2   3.0  1.0  3.0  26.00  0.0   7.9250
3   4.0  1.0  1.0  35.00  0.0  53.1000
4   5.0  0.0  3.0  35.00  0.0   8.0500
5   6.0  0.0  3.0  31.21  0.0   8.4583
6   7.0  0.0  1.0  54.00  0.0  51.8625
7   8.0  0.0  3.0   2.00  1.0  21.0750
8   9.0  1.0  3.0  27.00  2.0  11.1333
9  10.0  1.0  2.0  14.00  0.0  30.0708

In [32]:
df_new[3]=df_new[3].round().astype(int)   # age cannot be in flot

In [33]:
df_new.head(10)

      0    1    2   3  4        5
0   1.0  0.0  3.0  22  0   7.2500
1   2.0  1.0  1.0  38  0  71.2833
2   3.0  1.0  3.0  26  0   7.9250
3   4.0  1.0  1.0  35  0  53.1000
4   5.0  0.0  3.0  35  0   8.0500
5   6.0  0.0  3.0  31  0   8.4583
6   7.0  0.0  1.0  54  0  51.8625
7   8.0  0.0  3.0   2  1  21.0750
8   9.0  1.0  3.0  27  2  11.1333
9  10.0  1.0  2.0  14  0  30.0708