In [1]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df['Family_size']=df['Parch'] + df['SibSp']+ 1 
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [11]:
#introduce family type
# 0-small family 
# 1 medium family 
# 2 large family

def Family_type(data):
    if data == 1:
        return 0
    elif data <4:
        return 1
    else:
        return 2

In [12]:
df["Family_type"]=df['Family_size'].apply(Family_type)

In [13]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_size,Family_type
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,1,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,1,0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,5,2
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,3,1
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2,1

In [21]:
df['Title'] = df['Name'].str.split(", " , expand=True)[1].str.split("." , expand=True)[0]
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_size,Family_type,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,1,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,1,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,1,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,0,Mr
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,1,0,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,1,0,Mr
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,5,2,Master
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,3,1,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2,1,Mrs

### 1. Improves Model Performance
Good features help models discover patterns more easily.
Example:
Birth Year → Age
Age is usually more useful than birth year.

2. Helps Simple Models Perform Better
Sometimes:
Good Features + Logistic Regression
outperform
Poor Features + XGBoost
Feature quality often matters more than algorithm complexity.

3. Reveals Hidden Relationships
Example:
FamilySize = SibSp + Parch + 1
The model may learn family behavior better than from separate columns.

4. Makes Data More Meaningful
Example:
BMI = Weight / Height²
BMI carries more health information than weight or height alone.

5. Can Reduce Noise
Instead of exact age:
18, 19, 20, 21...
Create:
Child, Adult, Senior
which may generalize better.

6. Helps Handle Nonlinear Relationships
Example:x²
allows linear models to learn curved relationships.

7. Incorporates Domain Knowledge
Example:
Finance:
Debt-to-Income Ratio
These often become highly predictive features.

8. Better Interpretability
Features like:
Average Purchase Amount
Customer Lifetime Value
are easier to explain than raw transaction data.

Disadvantages of Feature Creation
1. Can Cause Overfitting
Creating too many features may cause the model to memorize training data.
Example:
x
x²
x³
x⁴
...
x²⁰
Model becomes overly complex.

2. Increases Dimensionality
More features mean:
More memory
More storage
Longer training time
This is called the curse of dimensionality.

3. Requires Domain Knowledge
Without understanding the problem:
Useful Feature Creation = Difficult
Bad features can hurt performance.

4. Risk of Data Leakage
A common beginner mistake.
Example:
Using future information to create a feature.
Exam Score → Predict Exam Pass
This leaks the answer into the model.

5. More Complex Pipeline
Instead of:
Raw Data → Model
you now have:
Raw Data
   ↓
Feature Creation
   ↓
Encoding
   ↓
Scaling
   ↓
Model
Maintenance becomes harder.

6. Some Features May Be Redundant
Example:
Area = Length × Width
Perimeter = 2(Length + Width)
Sometimes new features add little information.

7. Increased Computation Cost
Complex features may require:
groupby operations
aggregations
text processing
date calculations
which can slow training.