### Probability Ratio Encoding
#### Advantage :
1. Captures strong relationship with the target
2. Creates a monotonic and ordered feature
3. Handles high-cardinality categorical variables
4. Improves model interpretability
5. Reduces sparsity
6. Better separation than mean encoding

### disadvantage:
1. High risk of overfitting
2. Target leakage
3. Requires smoothing
4. Sensitive to noise
5. Less effective for tree-based models
6. Harder to interpret extreme values

In [56]:
import pandas as pd 
import numpy as np

In [57]:
df=pd.read_csv('titanic.csv',usecols=['Cabin','Survived'])

In [58]:
df.head()

   Survived Cabin
0         0   NaN
1         1   C85
2         1   NaN
3         1  C123
4         0   NaN

In [59]:
# replace nan with missingabs
df['Cabin'].fillna('Missing',inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_36392\413867737.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna('Missing',inplace=True)

In [60]:
df["Cabin"].unique()

array(['Missing', 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [61]:
len(df['Cabin'].unique())

148

In [62]:
df['Cabin']=df["Cabin"].astype(str).str[0]

In [63]:
df['Cabin'].unique()

array(['M', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [64]:
prob_df=df.groupby(['Cabin'])['Survived'].mean()

In [65]:
prob_df=pd.DataFrame(prob_df)

In [66]:
prob_df

       Survived
Cabin
A      0.466667
B      0.744681
C      0.593220
D      0.757576
E      0.750000
F      0.615385
G      0.500000
M      0.299854
T      0.000000

In [67]:
prob_df['Died']=1-prob_df["Survived"]

In [68]:
prob_df

       Survived      Died
Cabin
A      0.466667  0.533333
B      0.744681  0.255319
C      0.593220  0.406780
D      0.757576  0.242424
E      0.750000  0.250000
F      0.615385  0.384615
G      0.500000  0.500000
M      0.299854  0.700146
T      0.000000  1.000000

In [69]:
prob_df['probability_ratio']=prob_df['Survived']/prob_df['Died']

In [70]:
prob_df

       Survived      Died  probability_ratio
Cabin
A      0.466667  0.533333           0.875000
B      0.744681  0.255319           2.916667
C      0.593220  0.406780           1.458333
D      0.757576  0.242424           3.125000
E      0.750000  0.250000           3.000000
F      0.615385  0.384615           1.600000
G      0.500000  0.500000           1.000000
M      0.299854  0.700146           0.428274
T      0.000000  1.000000           0.000000

In [71]:
prob_ratio=prob_df['probability_ratio'].to_dict()
prob_ratio

{'A': 0.875,
 'B': 2.916666666666666,
 'C': 1.4583333333333333,
 'D': 3.125,
 'E': 3.0,
 'F': 1.6000000000000003,
 'G': 1.0,
 'M': 0.42827442827442824,
 'T': 0.0}

In [72]:
df['Cabin_endoded']=df['Cabin'].map(prob_ratio)

In [73]:
df.head()

   Survived Cabin  Cabin_endoded
0         0     M       0.428274
1         1     C       1.458333
2         1     M       0.428274
3         1     C       1.458333
4         0     M       0.428274

In [74]:
df.drop(columns='Cabin', axis=1,inplace=True)

In [75]:
df.head()

   Survived  Cabin_endoded
0         0       0.428274
1         1       1.458333
2         1       0.428274
3         1       1.458333
4         0       0.428274