### Ordinall NUmber Encoding 
#### - Rank(example degree, grade ,etc)

In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import datetime

In [19]:
today_date=datetime.datetime.today()
today_date

datetime.datetime(2025, 12, 23, 15, 27, 48, 817655)

In [18]:
today_date-datetime.timedelta(2)

datetime.datetime(2025, 12, 21, 15, 27, 14, 46020)

In [27]:
days=[today_date-datetime.timedelta(i) for i in range(15)]

In [32]:
df=pd.DataFrame(days)
df.columns=['day']

In [33]:
df.head()

                         day
0 2025-12-23 15:27:48.817655
1 2025-12-22 15:27:48.817655
2 2025-12-21 15:27:48.817655
3 2025-12-20 15:27:48.817655
4 2025-12-19 15:27:48.817655

In [50]:
df['day_name']=df['day'].dt.day_name()

In [51]:
df

                          day   day_name
0  2025-12-23 15:27:48.817655    Tuesday
1  2025-12-22 15:27:48.817655     Monday
2  2025-12-21 15:27:48.817655     Sunday
3  2025-12-20 15:27:48.817655   Saturday
4  2025-12-19 15:27:48.817655     Friday
5  2025-12-18 15:27:48.817655   Thursday
6  2025-12-17 15:27:48.817655  Wednesday
7  2025-12-16 15:27:48.817655    Tuesday
8  2025-12-15 15:27:48.817655     Monday
9  2025-12-14 15:27:48.817655     Sunday
10 2025-12-13 15:27:48.817655   Saturday
11 2025-12-12 15:27:48.817655     Friday
12 2025-12-11 15:27:48.817655   Thursday
13 2025-12-10 15:27:48.817655  Wednesday
14 2025-12-09 15:27:48.817655    Tuesday

In [56]:
dictionary={
    'Monday':1,'Tuesday':2, 'Wednesday':3, 'Thursday':4,'Friday':5,'Saturday':6,'Sunday':7
}

In [57]:
df['Ordinal_day_name']= df['day_name'].map(dictionary)

In [58]:
df

                          day   day_name  Ordinal_day_name
0  2025-12-23 15:27:48.817655    Tuesday                 2
1  2025-12-22 15:27:48.817655     Monday                 1
2  2025-12-21 15:27:48.817655     Sunday                 7
3  2025-12-20 15:27:48.817655   Saturday                 6
4  2025-12-19 15:27:48.817655     Friday                 5
5  2025-12-18 15:27:48.817655   Thursday                 4
6  2025-12-17 15:27:48.817655  Wednesday                 3
7  2025-12-16 15:27:48.817655    Tuesday                 2
8  2025-12-15 15:27:48.817655     Monday                 1
9  2025-12-14 15:27:48.817655     Sunday                 7
10 2025-12-13 15:27:48.817655   Saturday                 6
11 2025-12-12 15:27:48.817655     Friday                 5
12 2025-12-11 15:27:48.817655   Thursday                 4
13 2025-12-10 15:27:48.817655  Wednesday                 3
14 2025-12-09 15:27:48.817655    Tuesday                 2