#### One Hot Encoding With many Category in a Feature

In [67]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [68]:
df=pd.read_csv('mercedesbenz.csv',usecols=['X0','X1','X2', 'X3','X4','X5','X6'])
df.head()

   X0 X1  X2 X3 X4 X5 X6
0   k  v  at  a  d  u  j
1   k  t  av  e  d  y  l
2  az  w   n  c  d  x  j
3  az  t   n  f  d  x  l
4  az  v   n  f  d  h  d

In [69]:
df['X1'].unique()

array(['v', 't', 'w', 'b', 'r', 'l', 's', 'aa', 'c', 'a', 'e', 'h', 'z',
       'j', 'o', 'u', 'p', 'n', 'i', 'y', 'd', 'f', 'm', 'k', 'g', 'q',
       'ab'], dtype=object)

In [70]:
df.groupby(['X1'])['X1'].value_counts(ascending=True)

X1
a     143
aa    833
ab      3
b     592
c     121
d       3
e      33
f      23
g       6
h      29
i     203
j      22
k      17
l     590
m      32
n      19
o      82
p       9
q       3
r     251
s     598
t      31
u      37
v     408
w      52
y      23
z      46
Name: count, dtype: int64

In [71]:
[count for count in df['X1'].value_counts(ascending=False).iloc[:10].values]

[np.int64(833),
 np.int64(598),
 np.int64(592),
 np.int64(590),
 np.int64(408),
 np.int64(251),
 np.int64(203),
 np.int64(143),
 np.int64(121),
 np.int64(82)]

In [72]:
[count for count in df.X1.value_counts().sort_values(ascending=False).head(10).index]

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [73]:
df.groupby('X1').size().sort_values(ascending=False).head(10).index
# df.groupby('X1').size().sort_values(ascending=False)

Index(['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o'], dtype='object', name='X1')

In [74]:
top_10=[count for count in df.X1.value_counts().sort_values(ascending=False).head(10).index]

In [76]:
def encoding(df,feature,top_10):
    for item in top_10:
        df[item]=np.where(df[feature]==item,1,0)

In [77]:
encoding(df,'X1',top_10)

In [78]:
df.head()

   X0 X1  X2 X3 X4 X5 X6  aa  s  b  l  v  r  i  a  c  o
0   k  v  at  a  d  u  j   0  0  0  0  1  0  0  0  0  0
1   k  t  av  e  d  y  l   0  0  0  0  0  0  0  0  0  0
2  az  w   n  c  d  x  j   0  0  0  0  0  0  0  0  0  0
3  az  t   n  f  d  x  l   0  0  0  0  0  0  0  0  0  0
4  az  v   n  f  d  h  d   0  0  0  0  1  0  0  0  0  0

In [82]:
top_10.append('X1')
df[top_10].head(10)

   aa  s  b  l  v  r  i  a  c  o X1 X1
0   0  0  0  0  1  0  0  0  0  0  v  v
1   0  0  0  0  0  0  0  0  0  0  t  t
2   0  0  0  0  0  0  0  0  0  0  w  w
3   0  0  0  0  0  0  0  0  0  0  t  t
4   0  0  0  0  1  0  0  0  0  0  v  v
5   0  0  1  0  0  0  0  0  0  0  b  b
6   0  0  0  0  0  1  0  0  0  0  r  r
7   0  0  0  1  0  0  0  0  0  0  l  l
8   0  1  0  0  0  0  0  0  0  0  s  s
9   0  0  1  0  0  0  0  0  0  0  b  b

In [87]:
df[df['X1'].isin(top_10)]

      X0 X1  X2 X3 X4  X5 X6  aa  s  b  l  v  r  i  a  c  o
0      k  v  at  a  d   u  j   0  0  0  0  1  0  0  0  0  0
4     az  v   n  f  d   h  d   0  0  0  0  1  0  0  0  0  0
5      t  b   e  c  d   g  h   0  0  1  0  0  0  0  0  0  0
6     al  r   e  f  d   f  h   0  0  0  0  0  1  0  0  0  0
7      o  l  as  f  d   f  j   0  0  0  1  0  0  0  0  0  0
...   .. ..  .. .. ..  .. ..  .. .. .. .. .. .. .. .. .. ..
4204  ak  s  as  c  d  aa  d   0  1  0  0  0  0  0  0  0  0
4205   j  o   t  d  d  aa  h   0  0  0  0  0  0  0  0  0  1
4206  ak  v   r  a  d  aa  g   0  0  0  0  1  0  0  0  0  0
4207  al  r   e  f  d  aa  l   0  0  0  0  0  1  0  0  0  0
4208   z  r  ae  c  d  aa  g   0  0  0  0  0  1  0  0  0  0

[3821 rows x 17 columns]