#### suppose if you have more frequent categories, we just replave nan with new category
most used technique Yet

In [17]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
df=pd.read_csv('train_1.csv',usecols=['BsmtQual','FireplaceQu','GarageType','SalePrice'])
df.head()

  BsmtQual FireplaceQu GarageType  SalePrice
0       Gd         NaN     Attchd     208500
1       Gd          TA     Attchd     181500
2       Gd          TA     Attchd     223500
3       TA          Gd     Detchd     140000
4       Gd          TA     Attchd     250000

In [19]:
def implace_nan(df,variable):
    df[variable + "_nan"]=np.where(df[variable].isnull(),"Missing",df[variable])

In [20]:
for feature in ['BsmtQual','FireplaceQu','GarageType']: 
    implace_nan(df,feature)

In [21]:
df.head()

,BsmtQual,FireplaceQu,GarageType,SalePrice,BsmtQual_nan,FireplaceQu_nan,GarageType_nan
0,Gd,NaN,Attchd,208500,Gd,Missing,Attchd
1,Gd,TA,Attchd,181500,Gd,TA,Attchd
2,Gd,TA,Attchd,223500,Gd,TA,Attchd
3,TA,Gd,Detchd,140000,TA,Gd,Detchd
4,Gd,TA,Attchd,250000,Gd,TA,Attchd

In [22]:
df.isnull().sum()

BsmtQual            37
FireplaceQu        690
GarageType          81
SalePrice            0
BsmtQual_nan         0
FireplaceQu_nan      0
GarageType_nan       0
dtype: int64

In [24]:
df.drop(labels=['BsmtQual','FireplaceQu','GarageType'],axis=1,inplace=True)

In [25]:
df.head()

   SalePrice BsmtQual_nan FireplaceQu_nan GarageType_nan
0     208500           Gd         Missing         Attchd
1     181500           Gd              TA         Attchd
2     223500           Gd              TA         Attchd
3     140000           TA              Gd         Detchd
4     250000           Gd              TA         Attchd