#### Adding Variable To Capture NaN

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
# shows all the columns
pd.set_option('display.max_columns', None)

In [3]:
df=pd.read_csv('train_1.csv',usecols=['BsmtQual','FireplaceQu','GarageType','SalePrice'])
df.head()

  BsmtQual FireplaceQu GarageType  SalePrice
0       Gd         NaN     Attchd     208500
1       Gd          TA     Attchd     181500
2       Gd          TA     Attchd     223500
3       TA          Gd     Detchd     140000
4       Gd          TA     Attchd     250000

In [4]:
df['BsmtQual_nan']=np.where(df['BsmtQual'].isnull(),1,0)
df[df['BsmtQual'].isnull()].head()

    BsmtQual FireplaceQu GarageType  SalePrice  BsmtQual_nan
17       NaN         NaN    CarPort      90000             1
39       NaN         NaN        NaN      82000             1
90       NaN         NaN     Detchd     109900             1
102      NaN         NaN     Attchd     118964             1
156      NaN         NaN     Detchd     109500             1

In [8]:
most_frequent=df['BsmtQual'].mode()[0]

In [9]:
df['BsmtQual'].fillna(most_frequent, inplace=True)
df.head()

  BsmtQual FireplaceQu GarageType  SalePrice  BsmtQual_nan
0       Gd         NaN     Attchd     208500             0
1       Gd          TA     Attchd     181500             0
2       Gd          TA     Attchd     223500             0
3       TA          Gd     Detchd     140000             0
4       Gd          TA     Attchd     250000             0