#### Handling Categorical variable
#### One Hot Encoding

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df=pd.read_csv('titanic.csv')
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df=pd.read_csv('titanic.csv',usecols=['Sex'])
df.head()

      Sex
0    male
1  female
2  female
3  female
4    male

In [5]:
pd.get_dummies(data=df,columns=['Sex'],drop_first=False)

     Sex_female  Sex_male
0         False      True
1          True     False
2          True     False
3          True     False
4         False      True
..          ...       ...
886       False      True
887        True     False
888        True     False
889       False      True
890       False      True

[891 rows x 2 columns]

In [9]:
df=pd.read_csv('titanic.csv',usecols=['Embarked'])
df

    Embarked
0          S
1          C
2          S
3          S
4          S
..       ...
886        S
887        S
888        S
889        C
890        Q

[891 rows x 1 columns]

In [12]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [15]:
pd.get_dummies(data=df,drop_first=True,columns=['Embarked'],dtype=int)

     Embarked_Q  Embarked_S
0             0           1
1             0           0
2             0           1
3             0           1
4             0           1
..          ...         ...
886           0           1
887           0           1
888           0           1
889           0           0
890           1           0

[891 rows x 2 columns]