In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
pd.pandas.set_option('display.max_columns', None)
# shows all the columns

In [ ]:
df=pd.read_csv('train_1.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,df['SalePrice'],test_size=0.1,random_state=0)

In [ ]:
x_train.shape , x_test.shape

((1314, 81), (146, 81))

## For Missing Values

In [ ]:
feature_nan=[feature for feature in df.columns if df[feature].isnull().sum()>1 and df[feature].dtype == 'O']
df[feature_nan].head()

,Alley,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PoolQC,Fence,MiscFeature
0,NaN,BrkFace,Gd,TA,No,GLQ,Unf,NaN,Attchd,RFn,TA,TA,NaN,NaN,NaN
1,NaN,NaN,Gd,TA,Gd,ALQ,Unf,TA,Attchd,RFn,TA,TA,NaN,NaN,NaN
2,NaN,BrkFace,Gd,TA,Mn,GLQ,Unf,TA,Attchd,RFn,TA,TA,NaN,NaN,NaN
3,NaN,NaN,TA,Gd,No,ALQ,Unf,Gd,Detchd,Unf,TA,TA,NaN,NaN,NaN
4,NaN,BrkFace,Gd,TA,Av,GLQ,Unf,TA,Attchd,RFn,TA,TA,NaN,NaN,NaN

In [ ]:
for feature in feature_nan:
  print(" {} : {}% missing vallues".format(feature,np.round(df[feature].isnull().mean(),4)))

 Alley : 0.9377% missing vallues
 MasVnrType : 0.5973% missing vallues
 BsmtQual : 0.0253% missing vallues
 BsmtCond : 0.0253% missing vallues
 BsmtExposure : 0.026% missing vallues
 BsmtFinType1 : 0.0253% missing vallues
 BsmtFinType2 : 0.026% missing vallues
 FireplaceQu : 0.4726% missing vallues
 GarageType : 0.0555% missing vallues
 GarageFinish : 0.0555% missing vallues
 GarageQual : 0.0555% missing vallues
 GarageCond : 0.0555% missing vallues
 PoolQC : 0.9952% missing vallues
 Fence : 0.8075% missing vallues
 MiscFeature : 0.963% missing vallues

In [ ]:
# replace missing values with new labels
def replace_missing(df,feature_nan):
  data=df.copy()
  data[feature_nan]=data[feature_nan].fillna('Missing')
  return data

df=replace_missing(df,feature_nan)

In [ ]:
df[feature_nan].isnull().sum()

Alley           0
MasVnrType      0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
PoolQC          0
Fence           0
MiscFeature     0
dtype: int64

In [ ]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,Missing,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,Missing,Missing,Missing,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,Missing,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,Missing,Missing,Missing,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,Missing,Missing,Missing,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,Missing,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,Missing,Missing,Missing,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,Missing,Missing,Missing,0,12,2008,WD,Normal,250000

In [ ]:
# for numerical value
num_value_nan=[feature for feature in df.columns if df[feature].isnull().sum()>1 and df[feature].dtype != 'O']
df[num_value_nan].head()

   LotFrontage  MasVnrArea  GarageYrBlt
0         65.0       196.0       2003.0
1         80.0         0.0       1976.0
2         68.0       162.0       2001.0
3         60.0         0.0       1998.0
4         84.0       350.0       2000.0

In [ ]:
for feature in num_value_nan:
    print("{}: {}% missing value".format(feature,np.around(df[feature].isnull().mean(),4)))

LotFrontage: 0.1774% missing value
MasVnrArea: 0.0055% missing value
GarageYrBlt: 0.0555% missing value

In [ ]:
# replacing the numerical
for feature in num_value_nan:
  median_val=df[feature].median()

  df[feature + '_nan']=np.where(df[feature].isnull(),1,0)
  df[feature].fillna(median_val,inplace=True)

df[num_value_nan].isnull().sum()

/tmp/ipython-input-4074833092.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[feature].fillna(median_val,inplace=True)
/tmp/ipython-input-4074833092.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[feature].fillna(median_val,inplace=True)
/tmp/ipython-input-4074833092.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[feature].fillna(median_val,inplace=True)

LotFrontage    0
MasVnrArea     0
GarageYrBlt    0
dtype: int64

In [ ]:
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontage_nan,MasVnrArea_nan,GarageYrBlt_nan
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,Missing,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,Missing,Missing,Missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,Missing,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,Missing,Missing,Missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,Missing,Missing,Missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,Missing,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,Missing,Missing,Missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,Missing,Missing,Missing,0,12,2008,WD,Normal,250000,0,0,0
5,6,50,RL,85.0,14115,Pave,Missing,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1.5Fin,5,5,1993,1995,Gable,CompShg,VinylSd,VinylSd,Missing,0.0,TA,TA,Wood,Gd,TA,No,GLQ,732,Unf,0,64,796,GasA,Ex,Y,SBrkr,796,566,0,1362,1,0,1,1,1,1,TA,5,Typ,0,Missing,Attchd,1993.0,Unf,2,480,TA,TA,Y,40,30,0,320,0,0,Missing,MnPrv,Shed,700,10,2009,WD,Normal,143000,0,0,0
6,7,20,RL,75.0,10084,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,1Story,8,5,2004,2005,Gable,CompShg,VinylSd,VinylSd,Stone,186.0,Gd,TA,PConc,Ex,TA,Av,GLQ,1369,Unf,0,317,1686,GasA,Ex,Y,SBrkr,1694,0,0,1694,1,0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2004.0,RFn,2,636,TA,TA,Y,255,57,0,0,0,0,Missing,Missing,Missing,0,8,2007,WD,Normal,307000,0,0,0
7,8,60,RL,69.0,10382,Pave,Missing,IR1,Lvl,AllPub,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,7,6,1973,1973,Gable,CompShg,HdBoard,HdBoard,Stone,240.0,TA,TA,CBlock,Gd,TA,Mn,ALQ,859,BLQ,32,216,1107,GasA,Ex,Y,SBrkr,1107,983,0,2090,1,0,2,1,3,1,TA,7,Typ,2,TA,Attchd,1973.0,RFn,2,484,TA,TA,Y,235,204,228,0,0,0,Missing,Missing,Shed,350,11,2009,WD,Normal,200000,1,0,0
8,9,50,RM,51.0,6120,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Artery,Norm,1Fam,1.5Fin,7,5,1931,1950,Gable,CompShg,BrkFace,Wd Shng,Missing,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0,Unf,0,952,952,GasA,Gd,Y,FuseF,1022,752,0,1774,0,0,2,0,2,2,TA,8,Min1,2,TA,Detchd,1931.0,Unf,2,468,Fa,TA,Y,90,0,205,0,0,0,Missing,Missing,Missing,0,4,2008,WD,Abnorml,129900,0,0,0
9,10,190,RL,50.0,7420,Pave,Missing,Reg,Lvl,AllPub,Corner,Gtl,BrkSide,Artery,Artery,2fmCon,1.5Unf,5,6,1939,1950,Gable,CompShg,MetalSd,MetalSd,Missing,0.0,TA,TA,BrkTil,TA,TA,No,GLQ,851,Unf,0,140,991,GasA,Ex,Y,SBrkr,1077,0,0,1077,1,0,1,0,2,2,TA,5,Typ,2,TA,Attchd,1939.0,RFn,1,205,Gd,TA,Y,0,4,0,0,0,0,Missing,Missing,Missing,0,1,2008,WD,Normal,118000,0,0,0

In [ ]:
df[['YearBuilt','YearRemodAdd','GarageYrBlt']].head()

   YearBuilt  YearRemodAdd  GarageYrBlt
0       2003          2003       2003.0
1       1976          1976       1976.0
2       2001          2002       2001.0
3       1915          1970       1998.0
4       2000          2000       2000.0

## Numerical Variable

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 84 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               1460 non-null   int64
 1   MSSubClass       1460 non-null   int64
 2   MSZoning         1460 non-null   object
 3   LotFrontage      1460 non-null   float64
 4   LotArea          1460 non-null   int64
 5   Street           1460 non-null   object
 6   Alley            1460 non-null   object
 7   LotShape         1460 non-null   object
 8   LandContour      1460 non-null   object
 9   Utilities        1460 non-null   object
 10  LotConfig        1460 non-null   object
 11  LandSlope        1460 non-null   object
 12  Neighborhood     1460 non-null   object
 13  Condition1       1460 non-null   object
 14  Condition2       1460 non-null   object
 15  BldgType         1460 non-null   object
 16  HouseStyle       1460 non-null   object
 17  OverallQual      1460 non-null   int64
 18  OverallCond      1460 non-null   int64
 19  YearBuilt        1460 non-null   int64
 20  YearRemodAdd     1460 non-null   int64
 21  RoofStyle        1460 non-null   object
 22  RoofMatl         1460 non-null   object
 23  Exterior1st      1460 non-null   object
 24  Exterior2nd      1460 non-null   object
 25  MasVnrType       1460 non-null   object
 26  MasVnrArea       1460 non-null   float64
 27  ExterQual        1460 non-null   object
 28  ExterCond        1460 non-null   object
 29  Foundation       1460 non-null   object
 30  BsmtQual         1460 non-null   object
 31  BsmtCond         1460 non-null   object
 32  BsmtExposure     1460 non-null   object
 33  BsmtFinType1     1460 non-null   object
 34  BsmtFinSF1       1460 non-null   int64
 35  BsmtFinType2     1460 non-null   object
 36  BsmtFinSF2       1460 non-null   int64
 37  BsmtUnfSF        1460 non-null   int64
 38  TotalBsmtSF      1460 non-null   int64
 39  Heating          1460 non-null   object
 40  HeatingQC        1460 non-null   object
 41  CentralAir       1460 non-null   object
 42  Electrical       1459 non-null   object
 43  1stFlrSF         1460 non-null   int64
 44  2ndFlrSF         1460 non-null   int64
 45  LowQualFinSF     1460 non-null   int64
 46  GrLivArea        1460 non-null   int64
 47  BsmtFullBath     1460 non-null   int64
 48  BsmtHalfBath     1460 non-null   int64
 49  FullBath         1460 non-null   int64
 50  HalfBath         1460 non-null   int64
 51  BedroomAbvGr     1460 non-null   int64
 52  KitchenAbvGr     1460 non-null   int64
 53  KitchenQual      1460 non-null   object
 54  TotRmsAbvGrd     1460 non-null   int64
 55  Functional       1460 non-null   object
 56  Fireplaces       1460 non-null   int64
 57  FireplaceQu      1460 non-null   object
 58  GarageType       1460 non-null   object
 59  GarageYrBlt      1460 non-null   float64
 60  GarageFinish     1460 non-null   object
 61  GarageCars       1460 non-null   int64
 62  GarageArea       1460 non-null   int64
 63  GarageQual       1460 non-null   object
 64  GarageCond       1460 non-null   object
 65  PavedDrive       1460 non-null   object
 66  WoodDeckSF       1460 non-null   int64
 67  OpenPorchSF      1460 non-null   int64
 68  EnclosedPorch    1460 non-null   int64
 69  3SsnPorch        1460 non-null   int64
 70  ScreenPorch      1460 non-null   int64
 71  PoolArea         1460 non-null   int64
 72  PoolQC           1460 non-null   object
 73  Fence            1460 non-null   object
 74  MiscFeature      1460 non-null   object
 75  MiscVal          1460 non-null   int64
 76  MoSold           1460 non-null   int64
 77  YrSold           1460 non-null   int64
 78  SaleType         1460 non-null   object
 79  SaleCondition    1460 non-null   object
 80  SalePrice        1460 non-null   int64
 81  LotFrontage_nan  1460 non-null   int64
 82  MasVnrArea_nan   1460 non-null   int64
 83  GarageYrBlt_nan  1460 non-null   int64
dtypes: float64(3), int64(38), object(43)
memory usage: 958.3+ KB

In [ ]:
numerical_feature=['LotFrontage','LotArea','1stFlrSF','GrLivArea','SalePrice']
for feature in numerical_feature:
  df[feature]=np.log(df[feature])

Handling Rare categorical Variable

In [ ]:
# remove categorical variable which is present less than 1% of observation
categorical_feature=[feature for feature in df.columns if df[feature].dtype == 'O']

In [ ]:
categorical_feature

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [ ]:
max(df['SalePrice'])

13.534473028231162

In [ ]:
for feature in categorical_feature:
    temp=df.groupby(feature)['SalePrice'].count()/len(df)
    temp_df=temp[temp>0.01].index
    df[feature]=np.where(df[feature].isin(temp_df),df[feature],'Rare_var')

In [ ]:
df[categorical_feature].head(10)

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Missing,Attchd,RFn,TA,TA,Y,Missing,Missing,Missing,WD,Normal
1,RL,Pave,Missing,Reg,Lvl,AllPub,FR2,Gtl,Rare_var,Feedr,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,Missing,TA,TA,CBlock,Gd,TA,Gd,ALQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,TA,Attchd,RFn,TA,TA,Y,Missing,Missing,Missing,WD,Normal
2,RL,Pave,Missing,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,Mn,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,TA,Y,Missing,Missing,Missing,WD,Normal
3,RL,Pave,Missing,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,Missing,TA,TA,BrkTil,TA,Gd,No,ALQ,Unf,GasA,Gd,Y,SBrkr,Gd,Typ,Gd,Detchd,Unf,TA,TA,Y,Missing,Missing,Missing,WD,Abnorml
4,RL,Pave,Missing,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,TA,Y,Missing,Missing,Missing,WD,Normal
5,RL,Pave,Missing,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1.5Fin,Gable,CompShg,VinylSd,VinylSd,Missing,TA,TA,Rare_var,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Missing,Attchd,Unf,TA,TA,Y,Missing,MnPrv,Shed,WD,Normal
6,RL,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,1Story,Gable,CompShg,VinylSd,VinylSd,Stone,Gd,TA,PConc,Ex,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Gd,Attchd,RFn,TA,TA,Y,Missing,Missing,Missing,WD,Normal
7,RL,Pave,Missing,IR1,Lvl,AllPub,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,Gable,CompShg,HdBoard,HdBoard,Stone,TA,TA,CBlock,Gd,TA,Mn,ALQ,BLQ,GasA,Ex,Y,SBrkr,TA,Typ,TA,Attchd,RFn,TA,TA,Y,Missing,Missing,Shed,WD,Normal
8,RM,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Artery,Norm,1Fam,1.5Fin,Gable,CompShg,BrkFace,Wd Shng,Missing,TA,TA,BrkTil,TA,TA,No,Unf,Unf,GasA,Gd,Y,FuseF,TA,Min1,TA,Detchd,Unf,Fa,TA,Y,Missing,Missing,Missing,WD,Abnorml
9,RL,Pave,Missing,Reg,Lvl,AllPub,Corner,Gtl,BrkSide,Artery,Rare_var,2fmCon,Rare_var,Gable,CompShg,MetalSd,MetalSd,Missing,TA,TA,BrkTil,TA,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,TA,Attchd,RFn,Rare_var,TA,Y,Missing,Missing,Missing,WD,Normal

In [ ]:

for feature in categorical_feature:
    labels_ordered=df.groupby([feature])['SalePrice'].mean().sort_values().index
    labels_ordered={k:i for i,k in enumerate(labels_ordered,0)}
    df[feature]=df[feature].map(labels_ordered)

In [ ]:
df.head(50)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontage_nan,MasVnrArea_nan,GarageYrBlt_nan
0,1,60,3,4.174387,9.041922,1,2,0,1,1,0,0,14,2,1,3,5,7,5,2003,2003,0,0,10,10,2,196.0,2,3,4,3,3,1,6,706,5,0,150,856,2,4,1,3,6.752270,854,0,7.444249,1,0,2,1,3,1,2,8,4,0,1,4,2003.0,2,2,548,2,3,2,0,61,0,0,0,0,0,4,2,0,2,2008,2,3,12.247694,0,0,0
1,2,20,3,4.382027,9.169518,1,2,0,1,1,2,0,11,1,1,3,3,6,8,1976,1976,0,0,4,3,1,0.0,1,3,2,3,3,4,4,978,5,0,284,1262,2,4,1,3,7.140453,0,0,7.140453,0,1,2,0,3,1,1,6,4,1,3,4,1976.0,2,2,460,2,3,2,298,0,0,0,0,0,0,4,2,0,5,2007,2,3,12.109011,0,0,0
2,3,60,3,4.219508,9.328123,1,2,1,1,1,0,0,14,2,1,3,5,7,5,2001,2002,0,0,10,10,2,162.0,2,3,4,3,3,2,6,486,5,0,434,920,2,4,1,3,6.824374,866,0,7.487734,1,0,2,1,3,1,2,6,4,1,3,4,2001.0,2,2,608,2,3,2,0,42,0,0,0,0,0,4,2,0,9,2008,2,3,12.317167,0,0,0
3,4,70,3,4.094345,9.164296,1,2,1,1,1,1,0,16,2,1,3,5,7,5,1915,1970,0,0,2,4,1,0.0,1,3,1,2,4,1,4,216,5,0,540,756,2,3,1,3,6.867974,756,0,7.448334,1,0,1,0,3,1,2,7,4,1,4,2,1998.0,1,3,642,2,3,2,0,35,272,0,0,0,0,4,2,0,2,2006,2,0,11.849398,0,0,0
4,5,60,3,4.430817,9.565214,1,2,1,1,1,2,0,22,2,1,3,5,8,5,2000,2000,0,0,10,10,2,350.0,2,3,4,3,3,3,6,655,5,0,490,1145,2,4,1,3,7.043160,1053,0,7.695303,1,0,2,1,4,1,2,9,4,1,3,4,2000.0,2,3,836,2,3,2,192,84,0,0,0,0,0,4,2,0,12,2008,2,3,12.429216,0,0,0
5,6,50,3,4.442651,9.554993,1,2,1,1,1,0,0,9,2,1,3,1,5,5,1993,1995,0,0,10,10,1,0.0,1,3,3,3,3,1,6,732,5,0,64,796,2,4,1,3,6.679599,566,0,7.216709,1,0,1,1,1,1,1,5,4,0,1,4,1993.0,1,2,480,2,3,2,40,30,0,320,0,0,0,2,1,700,10,2009,2,3,11.870600,0,0,0
6,7,20,3,4.317488,9.218705,1,2,0,1,1,0,0,18,2,1,3,3,8,5,2004,2005,0,0,10,10,3,186.0,2,3,4,4,3,3,6,1369,5,0,317,1686,2,4,1,3,7.434848,0,0,7.434848,1,0,2,0,3,1,2,7,4,1,4,4,2004.0,2,2,636,2,3,2,255,57,0,0,0,0,0,4,2,0,8,2007,2,3,12.634603,0,0,0
7,8,60,3,4.234107,9.247829,1,2,1,1,1,1,0,12,5,1,3,5,7,6,1973,1973,0,0,6,5,3,240.0,1,3,2,3,3,2,4,859,1,32,216,1107,2,4,1,3,7.009409,983,0,7.644919,1,0,2,1,3,1,1,7,4,2,3,4,1973.0,2,2,484,2,3,2,235,204,228,0,0,0,0,4,1,350,11,2009,2,3,12.206073,1,0,0
8,9,50,1,3.931826,8.719317,1,2,0,1,1,0,0,4,0,1,3,1,7,5,1931,1950,0,0,8,4,1,0.0,1,3,1,2,3,1,5,0,5,0,952,952,2,3,1,1,6.929517,752,0,7.480992,0,0,2,0,2,2,1,8,3,2,3,2,1931.0,1,2,468,1,3,2,90,0,205,0,0,0,0,4,2,0,4,2008,2,0,11.774520,0,0,0
9,10,190,3,3.912023,8.911934,1,2,0,1,1,1,0,3,0,0,0,2,5,6,1939,1950,0,0,4,3,1,0.0,1,3,1,2,3,1,6,851,5,0,140,991,2,4,1,3,6.981935,0,0,6.981935,1,0,1,0,2,2,1,5,4,2,3,4,1939.0,2,1,205,3,3,2,0,4,0,0,0,0,0,4,2,0,1,2008,2,3,11.678440,0,0,0
10,11,20,3,4.248495,9.323669,1,2,0,1,1,0,0,6,2,1,3,3,5,5,1965,1965,2,0,6,5,1,0.0,1,3,2,2,3,1,1,906,5,0,134,1040,2,4,1,3,6.946976,0,0,6.946976,1,0,1,0,3,1,1,5,4,0,1,2,1965.0,1,1,384,2,3,2,0,0,0,0,0,0,0,4,2,0,2,2008,2,3,11.771436,0,0,0
11,12,60,3,4.442651,9.386308,1,2,1,1,1,0,0,21,2,1,3,5,9,5,2005,2006,2,0,3,4,3,286.0,3,3,4,4,3,1,6,998,5,0,177,1175,2,4,1,3,7.074963,1142,0,7.751045,1,0,3,0,4,1,3,11,4,2,4,5,2005.0,3,3,736,2,3,2,147,21,0,0,0,0,0,4,2,0,7,2006,3,4,12.751300,0,0,0
12,13,20,3,4.234107,9.470240,1,2,3,1,1,0,0,6,2,1,3,3,5,6,1962,1962,2,0,6,7,1,0.0,1,3,2,2,3,1,4,737,5,0,175,912,2,2,1,3,6.815640,0,0,6.815640,1,0,1,0,2,1,1,4,4,0,1,2,1962.0,1,1,352,2,3,2,140,0,0,0,176,0,0,4,2,0,9,2008,2,3,11.877569,1,0,0
13,14,20,3,4.510860,9.273503,1,2,1,1,1,0,0,14,2,1,3,3,7,5,2006,2007,0,0,10,10,3,306.0,2,3,4,3,3,3,5,0,5,0,1494,1494,2,4,1,3,7.309212,0,0,7.309212,0,0,2,0,3,1,2,7,4,1,4,4,2006.0,2,3,840,2,3,2,160,33,0,0,0,0,0,4,2,0,8,2007,3,4,12.540758,0,0,0
14,15,20,3,4.234107,9.298351,1,2,1,1,1,1,0,8,2,1,3,3,6,5,1960,1960,2,0,4,3,2,212.0,1,3,2,2,3,1,2,733,5,0,520,1253,2,2,1,3,7.133296,0,0,7.133296,1,0,1,1,2,1,1,5,4,1,2,4,1960.0,2,1,352,2,3,2,0,213,176,0,0,0,0,0,2,0,5,2008,2,3,11.964001,1,0,0
15,16,45,1,3.931826,8.719317,1,2,0,1,1,1,0,3,2,1,3,2,7,8,1929,2001,0,0,2,1,1,0.0,1,3,1,2,3,1,5,0,5,0,832,832,2,4,1,2,6.749931,0,0,6.749931,0,0,1,0,2,1,1,5,4,0,1,2,1991.0,1,2,576,2,3,2,48,112,0,0,0,0,0,3,2,0,7,2007,2,3,11.790557,0,0,0
16,17,20,3,4.234107,9.327323,1,2,1,1,1,4,0,8,2,1,3,3,6,7,1970,1970,0,0,2,1,2,180.0,1,3,2,2,3,1,4,578,5,0,426,1004,2,4,1,3,6.911747,0,0,6.911747,1,0,1,0,2,1,1,5,4,1,3,4,1970.0,3,2,480,2,3,2,0,0,0,0,0,0,0,4,1,700,3,2010,2,3,11.911702,1,0,0
17,18,90,3,4.276666,9.286468,1,2,0,1,1,0,0,6,2,1,2,3,4,5,1967,1967,0,0,4,3,1,0.0,1,3,0,0,1,0,0,0,0,0,0,0,2,2,1,3,7.167038,0,0,7.167038,0,0,2,0,2,2,1,6,4,0,1,1,1967.0,1,2,516,2,3,2,0,0,0,0,0,0,0,4,1,500,10,2006,2,3,11.407565,0,0,0
18,19,20,3,4.189655,9.524786,1,2,0,1,1,0,0,10,3,1,3,3,5,5,2004,2004,0,0,10,10,1,0.0,1,3,4,2,3,1,6,646,5,0,468,1114,2,4,1,3,7.015712,0,0,7.015712,1,0,1,1,3,1,2,6,4,0,1,2,2004.0,1,2,576,2,3,2,0,102,0,0,0,0,0,4,2,0,6,2008,2,3,11.976659,0,0,0
19,20,20,3,4.248495,8.930626,1,2,0,1,1,0,0,8,2,1,3,3,5,6,1958,1965,2,0,8,7,1,0.0,1,3,2,2,3,1,3,504,5,0,525,1029,2,2,1,3,7.199678,0,0,7.199678,0,0,1,0,3,1,1,6,3,0,1,4,1958.0,1,1,294,2,3,2,0,0,0,0,0,0,0,2,2,0,5,2009,0,0,11.842229,0,0,0
20,21,60,3,4.615121,9.562053,1,2,1,1,1,1,0,21,2,1,3,5,8,5,2005,2006,0,0,10,10,2,380.0,2,3,4,4,3,3,5,0,5,0,1158,1158,2,4,1,3,7.054450,1218,0,7.773174,0,0,3,1,4,1,2,9,4,1,4,5,2005.0,2,3,853,2,3,2,240,154,0,0,0,0,0,4,2,0,11,2006,3,4,12.692503,0,0,0
21,22,45,1,4.043051,8.915835,1,0,0,0,1,0,0,0,2,1,3,2,7,7,1930,1950,0,0,2,1,1,0.0,1,3,4,2,3,1,5,0,5,0,637,637,2,4,1,1,7.010312,0,0,7.010312,0,0,1,0,3,1,2,6,4,1,4,4,1930.0,1,1,280,2,3,0,0,0,205,0,0,0,0,3,2,0,6,2007,2,3,11.845103,0,0,0
22,23,20,3,4.317488,9.184202,1,2,0,1,1,0,0,14,2,1,3,3,8,5,2002,2002,2,0,10,10,2,281.0,2,3,4,3,3,1,5,0,5,0,1777,1777,2,4,1,3,7.492760,0,0,7.492760,0,0,2,0,3,1,2,7,4,1,4,4,2002.0,2,2,534,2,3,2,171,159,0,0,0,0,0,4,2,0,9,2008,2,3,12.345835,0,0,0
23,24,120,1,3.784190,8.348538,1,2,0,1,1,0,0,1,2,1,4,3,5,7,1976,1976,0,0,9,9,1,0.0,1,3,4,3,3,1,6,840,5,0,200,1040,2,2,1,3,6.966024,0,0,6.966024,1,0,1,0,3,1,1,6,4,1,3,4,1976.0,1,2,572,2,3,2,100,110,0,0,0,0,0,4,2,0,6,2007,2,3,11.774520,0,0,0
24,25,20,3,4.234107,9.017484,1,2,1,1,1,0,0,6,2,1,3,3,5,8,1968,2001,0,0,7,7,1,0.0,1,2,2,2,3,2,1,188,6,668,204,1060,2,4,1,3,6.966024,0,0,6.966024,1,0,1,0,3,1,2,6,4,1,3,4,1968.0,1,1,270,2,3,2,406,90,0,0,0,0,0,2,2,0,5,2010,2,3,11.944708,1,0,0
25,26,20,3,4.700480,9.563108,1,2,0,1,1,1,0,21,2,1,3,3,8,5,2007,2007,0,0,10,10,3,640.0,2,3,4,3,3,1,5,0,5,0,1566,1566,2,4,1,3,7.377759,0,0,7.377759,0,0,2,0,3,1,2,7,4,1,4,4,2007.0,2,3,890,2,3,2,0,56,0,0,0,0,0,4,2,0,7,2009,2,3,12.454104,0,0,0
26,27,20,3,4.094345,8.881836,1,2,0,1,1,1,0,8,2,1,3,3,5,7,1951,2000,0,0,2,1,1,0.0,1,3,2,2,3,2,2,234,2,486,180,900,2,2,1,3,6.802395,0,0,6.802395,0,1,1,0,3,1,2,5,4,0,1,2,2005.0,1,2,576,2,3,2,222,32,0,0,0,0,0,4,2,0,5,2010,2,3,11.811547,0,0,0
27,28,20,3,4.584967,9.348187,1,2,0,1,1,0,0,21,2,1,3,3,8,5,2007,2008,0,0,10,10,3,200.0,2,3,4,4,3,1,6,1218,5,0,486,1704,2,4,1,3,7.440734,0,0,7.440734,1,0,2,0,3,1,2,7,4,1,4,4,2008.0,2,3,772,2,3,2,0,50,0,0,0,0,0,4,2,0,5,2010,2,3,12.631340,0,0,0
28,29,20,3,3.850148,9.700208,1,2,1,1,1,4,0,8,2,1,3,3,5,6,1957,1997,0,0,4,3,1,0.0,1,3,2,2,3,4,2,1277,5,0,207,1484,2,2,1,3,7.377759,0,0,7.377759,1,0,1,0,2,1,1,6,4,2,4,4,1957.0,2,1,319,2,3,2,288,258,0,0,0,0,0,4,2,0,12,2006,2,3,12.242887,0,0,0
29,30,30,1,4.094345,8.752107,1,2,1,1,1,0,0,3,1,0,3,3,4,6,1927,1950,0,0,4,3,1,0.0,1,3,1,2,3,1,5,0,5,0,520,520,2,1,0,3,6.253829,0,0,6.253829,0,0,1,0,1,1,0,4,4,0,1,2,1920.0,1,1,240,1,3,2,49,0,87,0,0,0,0,4,2,0,5,2008,2,3,11.134589,0,0,0
30,31,70,0,3.912023,9.047821,1,1,0,1,1,0,0,0,1,1,3,5,4,4,1920,1950,1,0,8,8,1,0.0,1,0,1,2,3,1,5,0,5,0,649,649,2,2,0,3,6.475433,668,0,7.183112,0,0,1,0,3,1,1,6,4,0,1,2,1920.0,1,1,250,2,1,0,0,54,172,0,0,0,0,2,2,0,7,2008,2,3,10.596635,0,0,0
31,32,20,3,4.234107,9.052985,1,2,1,1,1,4,0,6,2,1,3,3,5,6,1966,2006,0,0,6,5,1,0.0,1,3,2,2,3,1,5,0,5,0,1228,1228,2,3,1,3,7.113142,0,0,7.113142,0,0,1,1,3,1,2,6,4,0,1,4,1966.0,1,1,271,2,3,2,0,65,0,0,0,0,0,2,2,0,6,2008,2,3,11.914048,1,0,0
32,33,20,3,4.442651,9.310095,1,2,0,1,1,1,0,14,2,1,3,3,8,5,2007,2007,0,0,10,10,1,0.0,2,3,4,4,3,3,5,0,5,0,1234,1234,2,4,1,3,7.118016,0,0,7.118016,0,0,2,0,3,1,2,7,4,0,1,4,2007.0,2,2,484,2,3,2,0,30,0,0,0,0,0,4,2,0,1,2008,2,3,12.100156,0,0,0
33,34,20,3,4.248495,9.264071,1,2,1,1,1,0,0,8,2,1,3,3,5,5,1959,1959,2,0,8,8,1,0.0,1,3,2,2,3,1,1,1018,5,0,380,1398,2,3,1,3,7.438384,0,0,7.438384,0,1,1,1,4,1,2,6,4,1,4,4,1959.0,2,2,447,2,3,2,0,38,0,0,0,0,0,4,2,0,4,2010,2,3,12.016726,0,0,0
34,35,120,3,4.094345,8.897409,1,2,0,1,1,0,0,21,2,1,4,3,9,5,2005,2005,2,0,4,3,2,246.0,3,3,4,4,3,1,6,1153,5,0,408,1561,2,4,1,3,7.353082,0,0,7.353082,1,0,2,0,2,1,3,6,4,1,4,4,2005.0,3,2,556,2,3,2,203,47,0,0,0,0,0,4,2,0,8,2007,2,3,12.533576,0,0,0
35,36,60,3,4.682131,9.504352,1,2,0,1,1,0,0,21,2,1,3,5,8,5,2004,2005,0,0,10,10,3,132.0,2,3,4,4,3,3,5,0,5,0,1117,1117,2,4,1,3,7.031741,1320,0,7.804659,0,0,3,1,4,1,2,9,4,1,4,5,2004.0,3,3,691,2,3,2,113,32,0,0,0,0,0,4,2,0,9,2006,2,3,12.641097,0,0,0
36,37,20,3,4.718499,9.292750,1,2,0,1,1,1,0,14,2,1,3,3,5,5,1994,1995,0,0,10,10,1,0.0,1,3,4,3,3,1,5,0,5,0,1097,1097,2,4,1,3,7.000334,0,0,7.000334,0,0,1,1,3,1,1,6,4,0,1,4,1995.0,1,2,672,2,3,2,392,64,0,0,0,0,0,4,2,0,6,2009,2,3,11.884489,0,0,0
37,38,20,3,4.304065,9.051579,1,2,0,1,1,0,0,8,2,1,3,3,5,6,1954,1990,2,0,2,1,2,650.0,1,3,2,2,3,1,1,1213,5,0,84,1297,2,3,1,3,7.167809,0,0,7.167809,0,1,1,0,3,1,1,5,4,1,3,4,1954.0,3,2,498,2,3,2,0,0,0,0,0,0,0,4,2,0,10,2009,2,3,11.938193,0,0,0
38,39,20,3,4.219508,8.977399,1,2,0,1,1,0,0,8,2,1,3,3,5,7,1953,2007,0,0,10,10,1,0.0,1,2,2,2,3,1,6,731,5,0,326,1057,2,2,1,3,6.963190,0,0,6.963190,1,0,1,0,3,1,2,5,4,0,1,2,1953.0,1,1,246,2,3,2,0,52,0,0,0,0,0,4,2,0,1,2010,2,0,11.599103,0,0,0
39,40,90,3,4.174387,8.706159,1,2,0,1,1,0,0,5,2,1,2,3,4,5,1955,1955,0,0,0,7,1,0.0,1,3,4,0,1,0,0,0,0,0,0,0,2,2,0,0,7.049255,0,0,7.049255,0,0,2,0,2,2,0,6,4,0,1,0,1980.0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,2,0,6,2008,2,1,11.314475,0,0,1
40,41,20,3,4.430817,9.066239,1,2,0,1,1,0,0,8,2,1,3,3,6,5,1965,1965,0,0,2,1,2,101.0,1,3,2,2,3,1,1,643,5,0,445,1088,2,4,1,3,7.188413,0,0,7.188413,0,0,2,0,3,1,1,6,4,1,3,4,1965.0,2,2,440,2,3,2,0,138,0,0,0,0,0,0,2,0,12,2006,2,0,11.982929,0,0,0
41,42,20,3,4.744932,9.735365,1,2,0,1,1,0,0,19,2,1,3,3,5,6,1959,1959,0,0,10,10,1,0.0,1,2,2,2,3,4,2,967,5,0,383,1350,2,3,1,3,7.191429,0,0,7.191429,0,1,1,1,2,1,1,5,4,2,4,4,1959.0,2,1,308,2,3,1,0,104,0,0,0,0,0,4,2,0,7,2007,2,3,12.043554,0,0,0
42,43,85,3,4.234107,9.124782,1,2,1,1,1,4,0,10,2,1,3,0,5,7,1983,1983,0,0,6,5,1,0.0,1,3,2,3,3,3,4,747,3,93,0,840,2,3,1,3,6.784457,0,0,6.784457,1,0,1,0,2,1,2,5,4,0,1,4,1983.0,2,2,504,2,2,2,240,0,0,0,0,0,0,2,2,0,12,2007,2,3,11.877569,1,0,0
43,44,20,3,4.234107,9.126959,1,2,1,1,1,4,0,14,2,1,3,3,5,6,1975,1980,2,0,10,10,1,0.0,1,3,2,3,3,3,3,280,1,491,167,938,2,2,1,3,6.843750,0,0,6.843750,1,0,1,0,3,1,1,5,4,0,1,2,1977.0,1,1,308,2,3,2,145,0,0,0,0,0,0,2,2,0,7,2008,2,3,11.777211,1,0,0
44,45,20,3,4.248495,8.980298,1,2,0,1,1,0,0,8,2,1,3,3,5,6,1959,1959,0,0,8,1,1,0.0,1,3,2,2,3,1,4,179,1,506,465,1150,2,4,1,2,7.047517,0,0,7.047517,1,0,1,0,3,1,1,6,4,0,1,4,1959.0,2,1,300,2,3,2,0,0,0,0,0,0,0,4,2,0,5,2006,2,3,11.856515,0,0,0
45,46,120,3,4.110874,8.943506,1,2,0,1,1,0,0,21,2,1,4,3,9,5,2005,2005,2,0,4,3,2,412.0,3,3,4,4,3,1,6,456,5,0,1296,1752,2,4,1,3,7.468513,0,0,7.468513,1,0,2,0,2,1,3,6,4,1,4,4,2005.0,2,2,576,2,3,2,196,82,0,0,0,0,0,4,2,0,2,2010,2,3,12.675764,0,0,0
46,47,50,3,3.871201,9.458918,1,2,1,1,1,4,0,9,2,1,3,1,7,5,2003,2003,0,0,10,10,1,0.0,2,3,4,4,3,1,6,1351,5,0,83,1434,2,4,1,3,7.325149,631,0,7.672758,1,0,1,1,1,1,2,6,4,1,5,4,2003.0,2,2,670,2,3,2,168,43,0,0,198,0,0,4,2,0,8,2009,2,0,12.387085,0,0,0
47,48,20,4,4.430817,9.314340,1,2,0,1,1,0,0,18,2,1,3,3,8,5,2006,2006,0,0,10,10,1,0.0,2,3,4,3,3,3,6,24,5,0,1632,1656,2,4,1,3,7.412160,0,0,7.412160,0,0,2,0,3,1,2,7,4,0,1,4,2006.0,2,3,826,2,3,2,0,146,0,0,0,0,0,4,2,0,7,2007,2,3,12.428015,0,0,0
48,49,190,1,3.496508,8.402007,1,2,0,1,1,0,0,4,2,1,0,5,4,5,1920,2008,0,0,4,3,1,0.0,1,3,1,2,3,1,5,0,5,0,736,736,2,3,1,3,6.601230,716,0,7.280697,0,0,2,0,2,3,1,8,4,0,1,0,1980.0,0,0,0,0,0,0,0,0,102,0,0,0,0,4,2,0,6,2009,3,4,11.635143,0,0,1
49,50,20,3,4.189655,8.954415,1,2,0,1,1,0,0,6,2,1,3,3,5,7,1966,1966,0,0,6,5,1,0.0,1,3,2,2,3,1,2,763,5,0,192,955,2,4,1,3,6.861711,0,0,6.861711,1,0,1,0,3,1,1,6,4,0,1,4,1966.0,1,1,386,2,3,2,0,0,0,0,0,0,0,2,2,0,1,2007,2,3,11.751942,0,0,0

#Scaling

In [ ]:
scaling_feature=[feature for feature in df.columns if feature not in ['Id','SalePrice'] ]

In [ ]:
len(scaling_feature)

82

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 84 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               1460 non-null   int64
 1   MSSubClass       1460 non-null   int64
 2   MSZoning         1460 non-null   int64
 3   LotFrontage      1460 non-null   float64
 4   LotArea          1460 non-null   float64
 5   Street           1460 non-null   int64
 6   Alley            1460 non-null   int64
 7   LotShape         1460 non-null   int64
 8   LandContour      1460 non-null   int64
 9   Utilities        1460 non-null   int64
 10  LotConfig        1460 non-null   int64
 11  LandSlope        1460 non-null   int64
 12  Neighborhood     1460 non-null   int64
 13  Condition1       1460 non-null   int64
 14  Condition2       1460 non-null   int64
 15  BldgType         1460 non-null   int64
 16  HouseStyle       1460 non-null   int64
 17  OverallQual      1460 non-null   int64
 18  OverallCond      1460 non-null   int64
 19  YearBuilt        1460 non-null   int64
 20  YearRemodAdd     1460 non-null   int64
 21  RoofStyle        1460 non-null   int64
 22  RoofMatl         1460 non-null   int64
 23  Exterior1st      1460 non-null   int64
 24  Exterior2nd      1460 non-null   int64
 25  MasVnrType       1460 non-null   int64
 26  MasVnrArea       1460 non-null   float64
 27  ExterQual        1460 non-null   int64
 28  ExterCond        1460 non-null   int64
 29  Foundation       1460 non-null   int64
 30  BsmtQual         1460 non-null   int64
 31  BsmtCond         1460 non-null   int64
 32  BsmtExposure     1460 non-null   int64
 33  BsmtFinType1     1460 non-null   int64
 34  BsmtFinSF1       1460 non-null   int64
 35  BsmtFinType2     1460 non-null   int64
 36  BsmtFinSF2       1460 non-null   int64
 37  BsmtUnfSF        1460 non-null   int64
 38  TotalBsmtSF      1460 non-null   int64
 39  Heating          1460 non-null   int64
 40  HeatingQC        1460 non-null   int64
 41  CentralAir       1460 non-null   int64
 42  Electrical       1460 non-null   int64
 43  1stFlrSF         1460 non-null   float64
 44  2ndFlrSF         1460 non-null   int64
 45  LowQualFinSF     1460 non-null   int64
 46  GrLivArea        1460 non-null   float64
 47  BsmtFullBath     1460 non-null   int64
 48  BsmtHalfBath     1460 non-null   int64
 49  FullBath         1460 non-null   int64
 50  HalfBath         1460 non-null   int64
 51  BedroomAbvGr     1460 non-null   int64
 52  KitchenAbvGr     1460 non-null   int64
 53  KitchenQual      1460 non-null   int64
 54  TotRmsAbvGrd     1460 non-null   int64
 55  Functional       1460 non-null   int64
 56  Fireplaces       1460 non-null   int64
 57  FireplaceQu      1460 non-null   int64
 58  GarageType       1460 non-null   int64
 59  GarageYrBlt      1460 non-null   float64
 60  GarageFinish     1460 non-null   int64
 61  GarageCars       1460 non-null   int64
 62  GarageArea       1460 non-null   int64
 63  GarageQual       1460 non-null   int64
 64  GarageCond       1460 non-null   int64
 65  PavedDrive       1460 non-null   int64
 66  WoodDeckSF       1460 non-null   int64
 67  OpenPorchSF      1460 non-null   int64
 68  EnclosedPorch    1460 non-null   int64
 69  3SsnPorch        1460 non-null   int64
 70  ScreenPorch      1460 non-null   int64
 71  PoolArea         1460 non-null   int64
 72  PoolQC           1460 non-null   int64
 73  Fence            1460 non-null   int64
 74  MiscFeature      1460 non-null   int64
 75  MiscVal          1460 non-null   int64
 76  MoSold           1460 non-null   int64
 77  YrSold           1460 non-null   int64
 78  SaleType         1460 non-null   int64
 79  SaleCondition    1460 non-null   int64
 80  SalePrice        1460 non-null   float64
 81  LotFrontage_nan  1460 non-null   int64
 82  MasVnrArea_nan   1460 non-null   int64
 83  GarageYrBlt_nan  1460 non-null   int64
dtypes: float64(7), int64(77)
memory usage: 958.3 KB

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit_transform(df[scaling_feature])

array([[0.23529412, 0.75      , 0.41820812, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.49506375, ..., 0.        , 0.        ,
        0.        ],
       [0.23529412, 0.75      , 0.434909  , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.29411765, 0.75      , 0.42385922, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.434909  , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.47117546, ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
df[scaling_feature]

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontage_nan,MasVnrArea_nan,GarageYrBlt_nan
0,60,3,4.174387,9.041922,1,2,0,1,1,0,0,14,2,1,3,5,7,5,2003,2003,0,0,10,10,2,196.0,2,3,4,3,3,1,6,706,5,0,150,856,2,4,1,3,6.752270,854,0,7.444249,1,0,2,1,3,1,2,8,4,0,1,4,2003.0,2,2,548,2,3,2,0,61,0,0,0,0,0,4,2,0,2,2008,2,3,0,0,0
1,20,3,4.382027,9.169518,1,2,0,1,1,2,0,11,1,1,3,3,6,8,1976,1976,0,0,4,3,1,0.0,1,3,2,3,3,4,4,978,5,0,284,1262,2,4,1,3,7.140453,0,0,7.140453,0,1,2,0,3,1,1,6,4,1,3,4,1976.0,2,2,460,2,3,2,298,0,0,0,0,0,0,4,2,0,5,2007,2,3,0,0,0
2,60,3,4.219508,9.328123,1,2,1,1,1,0,0,14,2,1,3,5,7,5,2001,2002,0,0,10,10,2,162.0,2,3,4,3,3,2,6,486,5,0,434,920,2,4,1,3,6.824374,866,0,7.487734,1,0,2,1,3,1,2,6,4,1,3,4,2001.0,2,2,608,2,3,2,0,42,0,0,0,0,0,4,2,0,9,2008,2,3,0,0,0
3,70,3,4.094345,9.164296,1,2,1,1,1,1,0,16,2,1,3,5,7,5,1915,1970,0,0,2,4,1,0.0,1,3,1,2,4,1,4,216,5,0,540,756,2,3,1,3,6.867974,756,0,7.448334,1,0,1,0,3,1,2,7,4,1,4,2,1998.0,1,3,642,2,3,2,0,35,272,0,0,0,0,4,2,0,2,2006,2,0,0,0,0
4,60,3,4.430817,9.565214,1,2,1,1,1,2,0,22,2,1,3,5,8,5,2000,2000,0,0,10,10,2,350.0,2,3,4,3,3,3,6,655,5,0,490,1145,2,4,1,3,7.043160,1053,0,7.695303,1,0,2,1,4,1,2,9,4,1,3,4,2000.0,2,3,836,2,3,2,192,84,0,0,0,0,0,4,2,0,12,2008,2,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,3,4.127134,8.976768,1,2,0,1,1,0,0,13,2,1,3,5,6,5,1999,2000,0,0,10,10,1,0.0,1,3,4,3,3,1,5,0,5,0,953,953,2,4,1,3,6.859615,694,0,7.406711,0,0,2,1,3,1,1,7,4,1,3,4,1999.0,2,2,460,2,3,2,0,40,0,0,0,0,0,4,2,0,8,2007,2,3,0,0,0
1456,20,3,4.442651,9.486076,1,2,0,1,1,0,0,12,2,1,3,3,6,6,1978,1988,0,0,7,7,3,119.0,1,3,2,3,3,1,4,790,2,163,589,1542,2,2,1,3,7.636752,0,0,7.636752,1,0,2,0,3,1,1,7,3,2,3,4,1978.0,1,2,500,2,3,2,349,0,0,0,0,0,0,2,2,0,2,2010,2,3,0,0,0
1457,70,3,4.189655,9.109636,1,2,0,1,1,0,0,16,2,1,3,5,7,9,1941,2006,0,0,9,9,1,0.0,3,2,3,2,4,1,6,275,5,0,877,1152,2,4,1,3,7.080026,1152,0,7.757906,0,0,2,0,4,1,2,9,4,2,4,4,1941.0,2,1,252,2,3,2,0,60,0,0,0,0,0,3,1,2500,5,2010,2,3,0,0,0
1458,20,3,4.219508,9.181632,1,2,0,1,1,0,0,8,2,1,3,3,5,6,1950,1996,2,0,4,3,1,0.0,1,3,2,2,3,2,6,49,2,1029,0,1078,2,3,1,2,6.982863,0,0,6.982863,1,0,1,0,2,1,2,5,4,0,1,4,1950.0,1,1,240,2,3,2,366,0,112,0,0,0,0,4,2,0,4,2010,2,3,0,0,0
1459,20,3,4.317488,9.204020,1,2,0,1,1,0,0,5,2,1,3,3,5,6,1965,1965,0,0,6,5,1,0.0,2,3,2,2,3,1,2,830,3,290,136,1256,2,3,1,3,7.135687,0,0,7.135687,1,0,1,1,3,1,1,6,4,0,1,4,1965.0,3,1,276,2,3,2,736,68,0,0,0,0,0,4,2,0,6,2008,2,3,0,0,0

In [ ]:
data=pd.concat([df[['Id','SalePrice']].reset_index(drop=True),pd.DataFrame(scaler.fit_transform(df[scaling_feature]), columns=scaling_feature)], axis=1)

In [ ]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontage_nan,MasVnrArea_nan,GarageYrBlt_nan
0,1,60,3,4.174387,9.041922,1,2,0,1,1,0,0,14,2,1,3,5,7,5,2003,2003,0,0,10,10,2,196.0,2,3,4,3,3,1,6,706,5,0,150,856,2,4,1,3,6.752270,854,0,7.444249,1,0,2,1,3,1,2,8,4,0,1,4,2003.0,2,2,548,2,3,2,0,61,0,0,0,0,0,4,2,0,2,2008,2,3,12.247694,0,0,0
1,2,20,3,4.382027,9.169518,1,2,0,1,1,2,0,11,1,1,3,3,6,8,1976,1976,0,0,4,3,1,0.0,1,3,2,3,3,4,4,978,5,0,284,1262,2,4,1,3,7.140453,0,0,7.140453,0,1,2,0,3,1,1,6,4,1,3,4,1976.0,2,2,460,2,3,2,298,0,0,0,0,0,0,4,2,0,5,2007,2,3,12.109011,0,0,0
2,3,60,3,4.219508,9.328123,1,2,1,1,1,0,0,14,2,1,3,5,7,5,2001,2002,0,0,10,10,2,162.0,2,3,4,3,3,2,6,486,5,0,434,920,2,4,1,3,6.824374,866,0,7.487734,1,0,2,1,3,1,2,6,4,1,3,4,2001.0,2,2,608,2,3,2,0,42,0,0,0,0,0,4,2,0,9,2008,2,3,12.317167,0,0,0
3,4,70,3,4.094345,9.164296,1,2,1,1,1,1,0,16,2,1,3,5,7,5,1915,1970,0,0,2,4,1,0.0,1,3,1,2,4,1,4,216,5,0,540,756,2,3,1,3,6.867974,756,0,7.448334,1,0,1,0,3,1,2,7,4,1,4,2,1998.0,1,3,642,2,3,2,0,35,272,0,0,0,0,4,2,0,2,2006,2,0,11.849398,0,0,0
4,5,60,3,4.430817,9.565214,1,2,1,1,1,2,0,22,2,1,3,5,8,5,2000,2000,0,0,10,10,2,350.0,2,3,4,3,3,3,6,655,5,0,490,1145,2,4,1,3,7.043160,1053,0,7.695303,1,0,2,1,4,1,2,9,4,1,3,4,2000.0,2,3,836,2,3,2,192,84,0,0,0,0,0,4,2,0,12,2008,2,3,12.429216,0,0,0

In [ ]:
data.to_csv('x_train.csv',index=False)