In [4]:
data_json = '''
[
  {
    "athlete": "Jim Walmsley",
    "year": 2019,
    "time": "14:09:28"
  },
  {
    "athlete": "Courtney Dauwalter",
    "year": 2023,
    "time": "15:29:34"
  },
  {
    "athlete": "Killian Jornet",
    "year": 2022,
    "time": null
  }
]
'''

In [8]:
import pandas as pd
from io import StringIO
df=pd.read_json(StringIO(data_json))
df.head()

              athlete  year      time
0        Jim Walmsley  2019  14:09:28
1  Courtney Dauwalter  2023  15:29:34
2      Killian Jornet  2022      None

In [12]:
df.to_json("new_jason",orient='records')
df

              athlete  year      time
0        Jim Walmsley  2019  14:09:28
1  Courtney Dauwalter  2023  15:29:34
2      Killian Jornet  2022      None

In [17]:
df = pd.DataFrame({
    "name": ["Killian", "Bob"],
    "laps": [48, 40]
})

In [19]:
df.to_json(orient='columns')

'{"name":{"0":"Killian","1":"Bob"},"laps":{"0":48,"1":40}}'

In [20]:
df.to_json(orient='split')

'{"columns":["name","laps"],"index":[0,1],"data":[["Killian",48],["Bob",40]]}'

In [24]:
data = [
  {
    "athlete": "Jim Walmsley",
    "years": [2016, 2018, 2019]
  }
]
pd.json_normalize(data)

        athlete               years
0  Jim Walmsley  [2016, 2018, 2019]

In [30]:
pd.json_normalize(data,"years",["athlete"])

      0       athlete
0  2016  Jim Walmsley
1  2018  Jim Walmsley
2  2019  Jim Walmsley