In [10]:
import pandas as pd
import numpy as np
data=np.arange(0,20).reshape(4,5)
df=pd.DataFrame(data,index=["row1","row2","row3","row4"],columns=["col1","col2","col3","col4","col5"])
df

      col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [11]:
df.head()

      col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      int64
 3   col4    4 non-null      int64
 4   col5    4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes

In [13]:
df.describe()

            col1       col2       col3       col4       col5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    7.500000   8.500000   9.500000  10.500000  11.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     3.750000   4.750000   5.750000   6.750000   7.750000
50%     7.500000   8.500000   9.500000  10.500000  11.500000
75%    11.250000  12.250000  13.250000  14.250000  15.250000
max    15.000000  16.000000  17.000000  18.000000  19.000000

In [20]:
#indexing 
print(df[['col2',"col3"]],type(df[['col2',"col3"]]))

      col2  col3
row1     1     2
row2     6     7
row3    11    12
row4    16    17 <class 'pandas.core.frame.DataFrame'>

In [19]:
print(df['col1'],type(df['col1']))

row1     0
row2     5
row3    10
row4    15
Name: col1, dtype: int64 <class 'pandas.core.series.Series'>

In [28]:
df.loc["row1":"row4"]

      col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [30]:
df.iloc[1:4,1:3]

      col2  col3
row2     6     7
row3    11    12
row4    16    17

In [32]:
df.iloc[:,0::3]

      col1  col4
row1     0     3
row2     5     8
row3    10    13
row4    15    18

In [34]:
df.iloc[:].values  #convert dataframe into arrays

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
data1=np.array([[1,0,5],[3,np.nan,4]])
df2=pd.DataFrame(data1)
df2

     0    1    2
0  1.0  0.0  5.0
1  3.0  NaN  4.0

In [46]:
df2.isnull().sum()

0    0
1    1
2    0
dtype: int64

In [48]:
df2.isnull()

       0      1      2
0  False  False  False
1  False   True  False

In [59]:
df["col3"].value_counts()

col3
2     1
7     1
12    1
17    1
Name: count, dtype: int64

In [60]:
df["col3"].unique()

array([ 2,  7, 12, 17])

In [79]:
df[df.iloc[2:,]>7]

      col1  col2  col3  col4  col5
row1   NaN   NaN   NaN   NaN   NaN
row2   NaN   NaN   NaN   NaN   NaN
row3  10.0  11.0  12.0  13.0  14.0
row4  15.0  16.0  17.0  18.0  19.0